INSERT INTO supplies (name, current_stock, min_stock, status, category, unit, updated_at)
VALUES 
('LECHE DESLACTOSADA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('LECHE ENTERA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POLVO FRAPPE', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POLVO TARO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POLVO RED VELVET', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POLVO COOKIES AND CREAM', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('CREMA BATIDA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MANGO CONGELADO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('FRUTOS ROJOS CONGELADOS', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('HARINA PARA CREPA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('CAFÉ DESCAFEINADO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POLVO DE CARNETION', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('LECHE NIDO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POLVO COFFE MATE', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('CROTONES', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('GALLETAS OREO', 4, 1, 'LOW', 'Insumos', 'unidad', NOW()),
('MIEL MAPLE', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MANTEQUILLA DE MANÍ', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('YOGURTH NATURAL', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('PLATANO', 4, 1, 'LOW', 'Insumos', 'unidad', NOW()),
('NUTELLA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('AGUA MINERAL', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('REFRESCOS', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JUGO MINI', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('SALAMI', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JAMON', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('PEPERONI', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MANTEQUILLA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('QUESO PHILADELPHIA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('3 QUESOS', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('AGUA EMBOTELLADA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('COCA COLA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MERMELADA DE FRESA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MERMELADA DE FRUTOS ROJOS', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MERMELADA DE ARANDANOS', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TÉ DE MANZANILLA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TÉ NEGRO CON DURAZNO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JARABE MOKA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JARABE FRUTOS ROJOS', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JARABE AVELLANA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JARABE CREMA IRLANDESA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JARABE MORA AZUL', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JARABE MANGO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('JARABE FRESA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POLVO MATCHA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('CRANBERRY', 4, 1, 'LOW', 'Insumos', 'unidad', NOW()),
('AGUA DE COCO CALAHUA', 4, 1, 'LOW', 'Insumos', 'unidad', NOW()),
('LECHERA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('LECHE EVAPORADA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('VALENTINA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('KETCHUP', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('RANCH', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MAYONESA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('MOSTAZA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('HERSHEY´S COCOA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('EXTRACTO DE VAINILLA', 4, 1, 'LOW', 'Insumos', 'unidad', NOW()),
('CHOCOLATE LIQUIDO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TÉ GENGIBRE Y LIMÓN', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TÉ BLANCO', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TÉ LAVANDA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TÉ SANCHA', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TÉ VERDE', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('HARINA PARA STRUDEL', 0, 1, 'OUT', 'Insumos', 'unidad', NOW()),
('CHAROLA PARA CREPA', 0, 1, 'OUT', 'Insumos', 'unidad', NOW()),
('VASOS DESECHABLES', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('TAPAS PARA VASOS', 5, 1, 'OK', 'Insumos', 'unidad', NOW()),
('POPOTES', 4, 1, 'LOW', 'Insumos', 'unidad', NOW()),
('CUCHARAS DESECHABLES', 4, 1, 'LOW', 'Insumos', 'unidad', NOW()),
('DESECHABLES PARA LLEVAR', 4, 1, 'LOW', 'Insumos', 'unidad', NOW())
ON CONFLICT (name) DO UPDATE SET
  current_stock = EXCLUDED.current_stock,
  min_stock = EXCLUDED.min_stock,
  status = EXCLUDED.status,
  updated_at = NOW();
